<?php

namespace Netgen\BlockManager\Item;

/**
 * Item is an entity injected into block, generated by executing a collection.
 */
interface ItemInterface
{
    /**
     * Returns the ID of the value from CMS from which this item is generated.
     *
     * @return int|string
     */
    public function getValueId();

    /**
     * Returns the type of the value from CMS from which this item is generated.
     *
     * @return string
     */
    public function getValueType();

    /**
     * Returns the name of the value from CMS from which this item is generated.
     *
     * @return string
     */
    public function getName();

    /**
     * Returns if the value from CMS is visible.
     *
     * @return bool
     */
    public function isVisible();

    /**
     * Returns the original value as supplied by the CMS.
     *
     * @return mixed
     */
    public function getObject();
}
