<?php

declare(strict_types=1);

return [
    'nglayouts_layout' => [
        ['id' => 1, 'status' => 0, 'uuid' => '81168ed3-86f9-55ea-b153-101f96f2c136', 'type' => '4_zones_a', 'name' => 'My layout', 'description' => 'My layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 1, 'status' => 1, 'uuid' => '81168ed3-86f9-55ea-b153-101f96f2c136', 'type' => '4_zones_a', 'name' => 'My layout', 'description' => 'My layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 2, 'status' => 0, 'uuid' => '71cbe281-430c-51d5-8e21-c3cc4e656dac', 'type' => '4_zones_b', 'name' => 'My other layout', 'description' => 'My other layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 2, 'status' => 1, 'uuid' => '71cbe281-430c-51d5-8e21-c3cc4e656dac', 'type' => '4_zones_b', 'name' => 'My other layout', 'description' => 'My other layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 2, 'status' => 2, 'uuid' => '71cbe281-430c-51d5-8e21-c3cc4e656dac', 'type' => '4_zones_b', 'name' => '', 'description' => 'My archived layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 3, 'status' => 0, 'uuid' => 'd8e55af7-cf62-5f28-ae15-331b457d82e9', 'type' => '4_zones_b', 'name' => 'My third layout', 'description' => 'My third layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 1, 'main_locale' => 'en'],
        ['id' => 3, 'status' => 1, 'uuid' => 'd8e55af7-cf62-5f28-ae15-331b457d82e9', 'type' => '4_zones_b', 'name' => 'My third layout', 'description' => 'My third layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 1, 'main_locale' => 'en'],
        ['id' => 4, 'status' => 0, 'uuid' => '8626a1ca-6413-5f54-acef-de7db06272ce', 'type' => '4_zones_b', 'name' => 'My fourth layout', 'description' => 'My fourth layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 5, 'status' => 0, 'uuid' => '399ad9ac-777a-50ba-945a-06e9f57add12', 'type' => '4_zones_b', 'name' => 'My fifth layout', 'description' => 'My fifth layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 1, 'main_locale' => 'en'],
        ['id' => 5, 'status' => 1, 'uuid' => '399ad9ac-777a-50ba-945a-06e9f57add12', 'type' => '4_zones_b', 'name' => 'My fifth layout', 'description' => 'My fifth layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 1, 'main_locale' => 'en'],
        ['id' => 6, 'status' => 1, 'uuid' => '7900306c-0351-5f0a-9b33-5d4f5a1f3943', 'type' => '4_zones_b', 'name' => 'My sixth layout', 'description' => 'My sixth layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 7, 'status' => 0, 'uuid' => '4b0202b3-5d06-5962-ae0c-bbeb25ee3503', 'type' => '4_zones_b', 'name' => 'My seventh layout', 'description' => 'My seventh layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
    ],
    'nglayouts_layout_translation' => [
        ['layout_id' => 1, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 1, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 1, 'status' => 0, 'locale' => 'hr'],
        ['layout_id' => 1, 'status' => 1, 'locale' => 'hr'],
        ['layout_id' => 2, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 2, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 2, 'status' => 2, 'locale' => 'en'],
        ['layout_id' => 3, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 3, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 4, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 5, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 5, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 6, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 7, 'status' => 0, 'locale' => 'en'],
    ],
    'nglayouts_block' => [
        ['id' => 1, 'status' => 0, 'uuid' => '01f0c14e-2e15-54a1-8b41-58a3a8a9a917', 'layout_id' => 1, 'depth' => 0, 'path' => '/1/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 1, 'status' => 1, 'uuid' => '01f0c14e-2e15-54a1-8b41-58a3a8a9a917', 'layout_id' => 1, 'depth' => 0, 'path' => '/1/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 2, 'status' => 0, 'uuid' => '39d3ab66-1589-540f-95c4-6381acb4f010', 'layout_id' => 1, 'depth' => 0, 'path' => '/2/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 2, 'status' => 1, 'uuid' => '39d3ab66-1589-540f-95c4-6381acb4f010', 'layout_id' => 1, 'depth' => 0, 'path' => '/2/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 3, 'status' => 0, 'uuid' => '96c7f078-a430-5a82-8d19-107182fb463f', 'layout_id' => 1, 'depth' => 0, 'path' => '/3/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 3, 'status' => 1, 'uuid' => '96c7f078-a430-5a82-8d19-107182fb463f', 'layout_id' => 1, 'depth' => 0, 'path' => '/3/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 4, 'status' => 0, 'uuid' => 'eaffe0e7-2cce-58c4-b1ca-ae29f7de61d1', 'layout_id' => 1, 'depth' => 0, 'path' => '/4/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 4, 'status' => 1, 'uuid' => 'eaffe0e7-2cce-58c4-b1ca-ae29f7de61d1', 'layout_id' => 1, 'depth' => 0, 'path' => '/4/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 5, 'status' => 0, 'uuid' => '7dd6e087-f8d3-53ed-88e5-d66bce9db93b', 'layout_id' => 2, 'depth' => 0, 'path' => '/5/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 5, 'status' => 1, 'uuid' => '7dd6e087-f8d3-53ed-88e5-d66bce9db93b', 'layout_id' => 2, 'depth' => 0, 'path' => '/5/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 5, 'status' => 2, 'uuid' => '7dd6e087-f8d3-53ed-88e5-d66bce9db93b', 'layout_id' => 2, 'depth' => 0, 'path' => '/5/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 0, 'uuid' => '5269f95e-7c32-5449-979f-760d1db3cf32', 'layout_id' => 2, 'depth' => 0, 'path' => '/6/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 1, 'uuid' => '5269f95e-7c32-5449-979f-760d1db3cf32', 'layout_id' => 2, 'depth' => 0, 'path' => '/6/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 2, 'uuid' => '5269f95e-7c32-5449-979f-760d1db3cf32', 'layout_id' => 2, 'depth' => 0, 'path' => '/6/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 7, 'status' => 0, 'uuid' => '8c4a5851-f2e0-5b46-a726-25230b5a3b9b', 'layout_id' => 2, 'depth' => 0, 'path' => '/7/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 7, 'status' => 1, 'uuid' => '8c4a5851-f2e0-5b46-a726-25230b5a3b9b', 'layout_id' => 2, 'depth' => 0, 'path' => '/7/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 7, 'status' => 2, 'uuid' => '8c4a5851-f2e0-5b46-a726-25230b5a3b9b', 'layout_id' => 2, 'depth' => 0, 'path' => '/7/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 8, 'status' => 0, 'uuid' => '842b223f-3d9c-58a3-97fd-d610a4479224', 'layout_id' => 2, 'depth' => 0, 'path' => '/8/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 8, 'status' => 1, 'uuid' => '842b223f-3d9c-58a3-97fd-d610a4479224', 'layout_id' => 2, 'depth' => 0, 'path' => '/8/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 8, 'status' => 2, 'uuid' => '842b223f-3d9c-58a3-97fd-d610a4479224', 'layout_id' => 2, 'depth' => 0, 'path' => '/8/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 9, 'status' => 0, 'uuid' => '151b13c3-d2f9-5180-95e2-68e8c3bdfd46', 'layout_id' => 3, 'depth' => 0, 'path' => '/9/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 9, 'status' => 1, 'uuid' => '151b13c3-d2f9-5180-95e2-68e8c3bdfd46', 'layout_id' => 3, 'depth' => 0, 'path' => '/9/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 10, 'status' => 0, 'uuid' => '3586b824-9283-5f6b-9477-94416143d680', 'layout_id' => 3, 'depth' => 0, 'path' => '/10/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 10, 'status' => 1, 'uuid' => '3586b824-9283-5f6b-9477-94416143d680', 'layout_id' => 3, 'depth' => 0, 'path' => '/10/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 11, 'status' => 0, 'uuid' => 'a344474c-79e5-52d0-8115-905aa2b5f1b6', 'layout_id' => 3, 'depth' => 0, 'path' => '/11/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 11, 'status' => 1, 'uuid' => 'a344474c-79e5-52d0-8115-905aa2b5f1b6', 'layout_id' => 3, 'depth' => 0, 'path' => '/11/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 12, 'status' => 0, 'uuid' => '154f933a-3212-5e08-a5b9-d7b93dd05c4f', 'layout_id' => 3, 'depth' => 0, 'path' => '/12/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 12, 'status' => 1, 'uuid' => '154f933a-3212-5e08-a5b9-d7b93dd05c4f', 'layout_id' => 3, 'depth' => 0, 'path' => '/12/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 13, 'status' => 0, 'uuid' => '5cbd086d-df78-5a11-8a12-2e1d4336b27a', 'layout_id' => 4, 'depth' => 0, 'path' => '/13/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 14, 'status' => 0, 'uuid' => 'bca72447-10ab-565f-9670-d54d3398763c', 'layout_id' => 4, 'depth' => 0, 'path' => '/14/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 15, 'status' => 0, 'uuid' => 'a8bbe914-42d4-541a-9ade-af466634447a', 'layout_id' => 4, 'depth' => 0, 'path' => '/15/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 16, 'status' => 0, 'uuid' => '7ff48c88-055e-5e32-8c1a-7411e98735e3', 'layout_id' => 4, 'depth' => 0, 'path' => '/16/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 17, 'status' => 0, 'uuid' => '98c95965-aa27-52e6-bd1f-c05274629e0a', 'layout_id' => 5, 'depth' => 0, 'path' => '/17/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 17, 'status' => 1, 'uuid' => '98c95965-aa27-52e6-bd1f-c05274629e0a', 'layout_id' => 5, 'depth' => 0, 'path' => '/17/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 18, 'status' => 0, 'uuid' => '4dec67bc-dc31-5464-b28c-a1fb5569d93d', 'layout_id' => 5, 'depth' => 0, 'path' => '/18/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 18, 'status' => 1, 'uuid' => '4dec67bc-dc31-5464-b28c-a1fb5569d93d', 'layout_id' => 5, 'depth' => 0, 'path' => '/18/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 19, 'status' => 0, 'uuid' => '785f5dab-c256-55d9-a3f0-e5e4cf72b6f7', 'layout_id' => 5, 'depth' => 0, 'path' => '/19/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 19, 'status' => 1, 'uuid' => '785f5dab-c256-55d9-a3f0-e5e4cf72b6f7', 'layout_id' => 5, 'depth' => 0, 'path' => '/19/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 20, 'status' => 0, 'uuid' => '7eb17cc5-46b7-5f32-bcb7-5173225fda25', 'layout_id' => 5, 'depth' => 0, 'path' => '/20/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 20, 'status' => 1, 'uuid' => '7eb17cc5-46b7-5f32-bcb7-5173225fda25', 'layout_id' => 5, 'depth' => 0, 'path' => '/20/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 21, 'status' => 1, 'uuid' => '66ba86eb-7581-594e-8623-026d7219aa9b', 'layout_id' => 6, 'depth' => 0, 'path' => '/21/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 22, 'status' => 1, 'uuid' => 'b4b46b40-662e-58d7-8d48-119f23ca255d', 'layout_id' => 6, 'depth' => 0, 'path' => '/22/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 23, 'status' => 1, 'uuid' => '98c318e5-2341-528e-8cf8-b23278b29884', 'layout_id' => 6, 'depth' => 0, 'path' => '/23/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 24, 'status' => 1, 'uuid' => 'fbee00cf-6105-5d43-a22e-38481bc85662', 'layout_id' => 6, 'depth' => 0, 'path' => '/24/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 25, 'status' => 0, 'uuid' => '43470783-4038-5004-af6a-49c1b236e0ec', 'layout_id' => 7, 'depth' => 0, 'path' => '/25/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 26, 'status' => 0, 'uuid' => 'bc5cb455-30d4-526f-86b0-e8fadc185ae0', 'layout_id' => 7, 'depth' => 0, 'path' => '/26/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 27, 'status' => 0, 'uuid' => 'b196de38-00f0-5246-92ee-d3622c510431', 'layout_id' => 7, 'depth' => 0, 'path' => '/27/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 28, 'status' => 0, 'uuid' => 'c6f62c00-ec61-55ce-8b77-46fde34a33f3', 'layout_id' => 7, 'depth' => 0, 'path' => '/28/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 29, 'status' => 0, 'uuid' => '346d7b5c-9302-5b36-baca-8c5c14f970ab', 'layout_id' => 7, 'depth' => 0, 'path' => '/29/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 31, 'status' => 0, 'uuid' => '28df256a-2467-5527-b398-9269ccc652de', 'layout_id' => 1, 'depth' => 1, 'path' => '/3/31/', 'parent_id' => 3, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'list', 'view_type' => 'list', 'item_view_type' => 'standard', 'name' => 'My block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 31, 'status' => 1, 'uuid' => '28df256a-2467-5527-b398-9269ccc652de', 'layout_id' => 1, 'depth' => 1, 'path' => '/3/31/', 'parent_id' => 3, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard_with_intro', 'name' => 'My published block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 32, 'status' => 0, 'uuid' => 'b07d3a85-bcdb-5af2-9b6f-deba36c700e7', 'layout_id' => 1, 'depth' => 1, 'path' => '/2/32/', 'parent_id' => 2, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard', 'name' => 'My other block', 'config' => '{"key": {"param1": false}}', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 32, 'status' => 1, 'uuid' => 'b07d3a85-bcdb-5af2-9b6f-deba36c700e7', 'layout_id' => 1, 'depth' => 1, 'path' => '/2/32/', 'parent_id' => 2, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard', 'name' => 'My other block', 'config' => '{"key": {"param1": false}}', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 33, 'status' => 0, 'uuid' => 'e666109d-f1db-5fd5-97fa-346f50e9ae59', 'layout_id' => 2, 'depth' => 1, 'path' => '/7/33/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'two_columns', 'view_type' => 'two_columns_50_50', 'item_view_type' => 'standard', 'name' => 'My third block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 33, 'status' => 1, 'uuid' => 'e666109d-f1db-5fd5-97fa-346f50e9ae59', 'layout_id' => 2, 'depth' => 1, 'path' => '/7/33/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'two_columns', 'view_type' => 'two_columns_50_50', 'item_view_type' => 'standard', 'name' => 'My third block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 33, 'status' => 2, 'uuid' => 'e666109d-f1db-5fd5-97fa-346f50e9ae59', 'layout_id' => 2, 'depth' => 1, 'path' => '/7/33/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'two_columns', 'view_type' => 'two_columns_50_50', 'item_view_type' => 'standard', 'name' => 'My third block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 34, 'status' => 0, 'uuid' => '42446cc9-24c3-573c-9022-6b3a764727b5', 'layout_id' => 2, 'depth' => 1, 'path' => '/6/34/', 'parent_id' => 6, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'title', 'view_type' => 'title', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 34, 'status' => 1, 'uuid' => '42446cc9-24c3-573c-9022-6b3a764727b5', 'layout_id' => 2, 'depth' => 1, 'path' => '/6/34/', 'parent_id' => 6, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'title', 'view_type' => 'title', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 34, 'status' => 2, 'uuid' => '42446cc9-24c3-573c-9022-6b3a764727b5', 'layout_id' => 2, 'depth' => 1, 'path' => '/6/34/', 'parent_id' => 6, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'title', 'view_type' => 'title', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 35, 'status' => 0, 'uuid' => 'c2a30ea3-95ef-55b0-a584-fbcfd93cec9e', 'layout_id' => 1, 'depth' => 1, 'path' => '/3/35/', 'parent_id' => 3, 'placeholder' => 'root', 'position' => 1, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 35, 'status' => 1, 'uuid' => 'c2a30ea3-95ef-55b0-a584-fbcfd93cec9e', 'layout_id' => 1, 'depth' => 1, 'path' => '/3/35/', 'parent_id' => 3, 'placeholder' => 'root', 'position' => 1, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 36, 'status' => 0, 'uuid' => 'b40aa688-b8e8-5e07-bf82-4a97e5ed8bad', 'layout_id' => 2, 'depth' => 1, 'path' => '/7/36/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 1, 'definition_identifier' => 'title', 'view_type' => 'title', 'item_view_type' => 'standard', 'name' => 'My sixth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 37, 'status' => 0, 'uuid' => '129f51de-a535-5094-8517-45d672e06302', 'layout_id' => 2, 'depth' => 2, 'path' => '/7/33/37/', 'parent_id' => 33, 'placeholder' => 'left', 'position' => 0, 'definition_identifier' => 'text', 'view_type' => 'text', 'item_view_type' => 'standard', 'name' => 'My seventh block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 37, 'status' => 1, 'uuid' => '129f51de-a535-5094-8517-45d672e06302', 'layout_id' => 2, 'depth' => 2, 'path' => '/7/33/37/', 'parent_id' => 33, 'placeholder' => 'left', 'position' => 0, 'definition_identifier' => 'text', 'view_type' => 'text', 'item_view_type' => 'standard', 'name' => 'My seventh block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 37, 'status' => 2, 'uuid' => '129f51de-a535-5094-8517-45d672e06302', 'layout_id' => 2, 'depth' => 2, 'path' => '/7/33/37/', 'parent_id' => 33, 'placeholder' => 'left', 'position' => 0, 'definition_identifier' => 'text', 'view_type' => 'text', 'item_view_type' => 'standard', 'name' => 'My seventh block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 38, 'status' => 0, 'uuid' => 'a2806e8a-ea8c-5c3b-8f84-2cbdae1a07f6', 'layout_id' => 2, 'depth' => 1, 'path' => '/7/38/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 2, 'definition_identifier' => 'column', 'view_type' => 'column', 'item_view_type' => 'standard', 'name' => 'My eight block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
    ],
    'nglayouts_block_translation' => [
        ['block_id' => 1, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 1, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 2, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 2, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 3, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 3, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 4, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 4, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 5, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 5, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 5, 'status' => 2, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 6, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 6, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 6, 'status' => 2, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 7, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 7, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 7, 'status' => 2, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 8, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 8, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 8, 'status' => 2, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 9, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 9, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 10, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 10, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 11, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 11, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 12, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 12, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 13, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 14, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 15, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 16, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 17, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 17, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 18, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 18, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 19, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 19, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 20, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 20, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 21, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 22, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 23, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 24, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 25, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 26, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 27, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 28, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 29, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 31, 'status' => 0, 'locale' => 'en', 'parameters' => '{"number_of_columns": 2, "css_class": "css-class", "css_id": "css-id"}'],
        ['block_id' => 31, 'status' => 1, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 31, 'status' => 0, 'locale' => 'hr', 'parameters' => '{"css_class": "css-class-hr", "css_id": "css-id"}'],
        ['block_id' => 31, 'status' => 1, 'locale' => 'hr', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 32, 'status' => 0, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 32, 'status' => 1, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 32, 'status' => 0, 'locale' => 'hr', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 32, 'status' => 1, 'locale' => 'hr', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 33, 'status' => 0, 'locale' => 'en', 'parameters' => '{}'],
        ['block_id' => 33, 'status' => 1, 'locale' => 'en', 'parameters' => '{}'],
        ['block_id' => 33, 'status' => 2, 'locale' => 'en', 'parameters' => '{}'],
        ['block_id' => 34, 'status' => 0, 'locale' => 'en', 'parameters' => '{"tag": "h3", "title": "Title"}'],
        ['block_id' => 34, 'status' => 1, 'locale' => 'en', 'parameters' => '{"tag": "h3", "title": "Title"}'],
        ['block_id' => 34, 'status' => 2, 'locale' => 'en', 'parameters' => '{"tag": "h3", "title": "Title"}'],
        ['block_id' => 35, 'status' => 0, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 35, 'status' => 1, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 36, 'status' => 0, 'locale' => 'en', 'parameters' => '{"tag": "h3", "title": "Title", "css_class": "CSS class"}'],
        ['block_id' => 37, 'status' => 0, 'locale' => 'en', 'parameters' => '{"content": "Text"}'],
        ['block_id' => 37, 'status' => 1, 'locale' => 'en', 'parameters' => '{"content": "Text"}'],
        ['block_id' => 37, 'status' => 2, 'locale' => 'en', 'parameters' => '{"content": "Text"}'],
        ['block_id' => 38, 'status' => 0, 'locale' => 'en', 'parameters' => '{}'],
    ],
    'nglayouts_zone' => [
        ['identifier' => 'top', 'layout_id' => 1, 'status' => 0, 'root_block_id' => 1, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 1, 'status' => 1, 'root_block_id' => 1, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 1, 'status' => 0, 'root_block_id' => 2, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 1, 'status' => 1, 'root_block_id' => 2, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 1, 'status' => 0, 'root_block_id' => 3, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 1, 'status' => 1, 'root_block_id' => 3, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 1, 'status' => 0, 'root_block_id' => 4, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 1, 'status' => 1, 'root_block_id' => 4, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 2, 'status' => 0, 'root_block_id' => 5, 'linked_layout_id' => 3, 'linked_zone_identifier' => 'top'],
        ['identifier' => 'top', 'layout_id' => 2, 'status' => 1, 'root_block_id' => 5, 'linked_layout_id' => 3, 'linked_zone_identifier' => 'top'],
        ['identifier' => 'top', 'layout_id' => 2, 'status' => 2, 'root_block_id' => 5, 'linked_layout_id' => 3, 'linked_zone_identifier' => 'top'],
        ['identifier' => 'left', 'layout_id' => 2, 'status' => 0, 'root_block_id' => 6, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 2, 'status' => 1, 'root_block_id' => 6, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 2, 'status' => 2, 'root_block_id' => 6, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 2, 'status' => 0, 'root_block_id' => 7, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 2, 'status' => 1, 'root_block_id' => 7, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 2, 'status' => 2, 'root_block_id' => 7, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 2, 'status' => 0, 'root_block_id' => 8, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 2, 'status' => 1, 'root_block_id' => 8, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 2, 'status' => 2, 'root_block_id' => 8, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 3, 'status' => 0, 'root_block_id' => 9, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 3, 'status' => 0, 'root_block_id' => 10, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 3, 'status' => 0, 'root_block_id' => 11, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 3, 'status' => 0, 'root_block_id' => 12, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 3, 'status' => 1, 'root_block_id' => 9, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 3, 'status' => 1, 'root_block_id' => 10, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 3, 'status' => 1, 'root_block_id' => 11, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 3, 'status' => 1, 'root_block_id' => 12, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 4, 'status' => 0, 'root_block_id' => 13, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 4, 'status' => 0, 'root_block_id' => 14, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 4, 'status' => 0, 'root_block_id' => 15, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 4, 'status' => 0, 'root_block_id' => 16, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 5, 'status' => 0, 'root_block_id' => 17, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 5, 'status' => 0, 'root_block_id' => 18, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 5, 'status' => 0, 'root_block_id' => 19, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 5, 'status' => 0, 'root_block_id' => 20, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 5, 'status' => 1, 'root_block_id' => 17, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 5, 'status' => 1, 'root_block_id' => 18, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 5, 'status' => 1, 'root_block_id' => 19, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 5, 'status' => 1, 'root_block_id' => 20, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 6, 'status' => 1, 'root_block_id' => 21, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 6, 'status' => 1, 'root_block_id' => 22, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 6, 'status' => 1, 'root_block_id' => 23, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 6, 'status' => 1, 'root_block_id' => 24, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 25, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 26, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 27, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 28, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        // This zone does not exist in a layout but is used in tests for layouts which had it's layout type config changed
        ['identifier' => 'center', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 29, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
    ],
    'nglayouts_collection' => [
        ['id' => 1, 'status' => 0, 'uuid' => 'a79dde13-1f5c-51a6-bea9-b766236be49e', 'start' => 0, 'length' => null, 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 2, 'status' => 1, 'uuid' => '45a6e6f5-0ae7-588b-bf2a-0e4cc24ec60a', 'start' => 0, 'length' => null, 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 3, 'status' => 0, 'uuid' => 'da050624-8ae0-5fb9-ae85-092bf8242b89', 'start' => 4, 'length' => 2, 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 3, 'status' => 1, 'uuid' => 'da050624-8ae0-5fb9-ae85-092bf8242b89', 'start' => 4, 'length' => 2, 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 4, 'status' => 0, 'uuid' => '08937ca0-18f4-5806-84df-8c132c36cabe', 'start' => 0, 'length' => null, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 4, 'status' => 1, 'uuid' => '08937ca0-18f4-5806-84df-8c132c36cabe', 'start' => 0, 'length' => null, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 0, 'uuid' => '00872ad1-60e2-5947-95c2-e2eb75427af6', 'start' => 10, 'length' => 5, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 1, 'uuid' => '00872ad1-60e2-5947-95c2-e2eb75427af6', 'start' => 10, 'length' => 5, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 2, 'uuid' => '00872ad1-60e2-5947-95c2-e2eb75427af6', 'start' => 10, 'length' => 5, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
    ],
    'nglayouts_collection_translation' => [
        ['collection_id' => 1, 'status' => 0, 'locale' => 'en'],
        ['collection_id' => 1, 'status' => 0, 'locale' => 'hr'],
        ['collection_id' => 2, 'status' => 1, 'locale' => 'en'],
        ['collection_id' => 2, 'status' => 1, 'locale' => 'hr'],
        ['collection_id' => 3, 'status' => 0, 'locale' => 'en'],
        ['collection_id' => 3, 'status' => 0, 'locale' => 'hr'],
        ['collection_id' => 3, 'status' => 1, 'locale' => 'en'],
        ['collection_id' => 3, 'status' => 1, 'locale' => 'hr'],
        ['collection_id' => 4, 'status' => 0, 'locale' => 'en'],
        ['collection_id' => 4, 'status' => 1, 'locale' => 'en'],
        ['collection_id' => 6, 'status' => 0, 'locale' => 'en'],
        ['collection_id' => 6, 'status' => 1, 'locale' => 'en'],
        ['collection_id' => 6, 'status' => 2, 'locale' => 'en'],
    ],
    'nglayouts_collection_item' => [
        ['id' => 1, 'status' => 0, 'collection_id' => 1, 'position' => 0, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 2, 'status' => 0, 'collection_id' => 1, 'position' => 1, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 3, 'status' => 0, 'collection_id' => 1, 'position' => 2, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 4, 'status' => 1, 'collection_id' => 2, 'position' => 1, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 5, 'status' => 1, 'collection_id' => 2, 'position' => 2, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 6, 'status' => 1, 'collection_id' => 2, 'position' => 5, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 7, 'status' => 0, 'collection_id' => 3, 'position' => 2, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 7, 'status' => 1, 'collection_id' => 3, 'position' => 2, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 8, 'status' => 0, 'collection_id' => 3, 'position' => 3, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 8, 'status' => 1, 'collection_id' => 3, 'position' => 3, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 9, 'status' => 0, 'collection_id' => 3, 'position' => 5, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 9, 'status' => 1, 'collection_id' => 3, 'position' => 5, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 10, 'status' => 0, 'collection_id' => 4, 'position' => 2, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 10, 'status' => 1, 'collection_id' => 4, 'position' => 2, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 11, 'status' => 0, 'collection_id' => 4, 'position' => 3, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 11, 'status' => 1, 'collection_id' => 4, 'position' => 3, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 12, 'status' => 0, 'collection_id' => 4, 'position' => 5, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 12, 'status' => 1, 'collection_id' => 4, 'position' => 5, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
    ],
    'nglayouts_collection_query' => [
        ['id' => 1, 'status' => 1, 'collection_id' => 2, 'type' => 'my_query_type'],
        ['id' => 2, 'status' => 0, 'collection_id' => 3, 'type' => 'my_query_type'],
        ['id' => 2, 'status' => 1, 'collection_id' => 3, 'type' => 'my_query_type'],
        ['id' => 4, 'status' => 0, 'collection_id' => 4, 'type' => 'my_query_type'],
        ['id' => 4, 'status' => 1, 'collection_id' => 4, 'type' => 'my_query_type'],
    ],
    'nglayouts_collection_query_translation' => [
        ['query_id' => 1, 'status' => 1, 'locale' => 'en', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 1, 'status' => 1, 'locale' => 'hr', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 2, 'status' => 0, 'locale' => 'en', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 2, 'status' => 0, 'locale' => 'hr', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 2, 'status' => 1, 'locale' => 'en', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 2, 'status' => 1, 'locale' => 'hr', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 4, 'status' => 0, 'locale' => 'en', 'parameters' => '{"parent_location_id": 71, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 4, 'status' => 1, 'locale' => 'en', 'parameters' => '{"parent_location_id": 71, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
    ],
    'nglayouts_block_collection' => [
        ['block_id' => 31, 'block_status' => 0, 'collection_id' => 1, 'collection_status' => 0, 'identifier' => 'default'],
        ['block_id' => 31, 'block_status' => 0, 'collection_id' => 3, 'collection_status' => 0, 'identifier' => 'featured'],
        ['block_id' => 31, 'block_status' => 1, 'collection_id' => 2, 'collection_status' => 1, 'identifier' => 'default'],
        ['block_id' => 31, 'block_status' => 1, 'collection_id' => 3, 'collection_status' => 1, 'identifier' => 'featured'],
        ['block_id' => 35, 'block_status' => 0, 'collection_id' => 4, 'collection_status' => 0, 'identifier' => 'default'],
        ['block_id' => 35, 'block_status' => 1, 'collection_id' => 4, 'collection_status' => 1, 'identifier' => 'default'],
        ['block_id' => 37, 'block_status' => 0, 'collection_id' => 6, 'collection_status' => 0, 'identifier' => 'default'],
        ['block_id' => 37, 'block_status' => 1, 'collection_id' => 6, 'collection_status' => 1, 'identifier' => 'default'],
        ['block_id' => 37, 'block_status' => 2, 'collection_id' => 6, 'collection_status' => 2, 'identifier' => 'default'],
    ],
    'nglayouts_role' => [
        ['id' => 1, 'status' => 1, 'name' => 'Admin', 'identifier' => 'admin', 'description' => 'Admin role'],
        ['id' => 2, 'status' => 0, 'name' => 'Editor', 'identifier' => 'editor', 'description' => 'Editor role'],
        ['id' => 2, 'status' => 1, 'name' => 'Editor', 'identifier' => 'editor', 'description' => 'Editor role'],
        ['id' => 2, 'status' => 2, 'name' => 'Editor', 'identifier' => 'editor', 'description' => 'Editor role'],
    ],
    'nglayouts_role_policy' => [
        ['id' => 1, 'status' => 1, 'role_id' => 1, 'component' => null, 'permission' => null, 'limitations' => '{}'],
        ['id' => 2, 'status' => 0, 'role_id' => 2, 'component' => 'block', 'permission' => 'add', 'limitations' => '{}'],
        ['id' => 2, 'status' => 1, 'role_id' => 2, 'component' => 'block', 'permission' => 'add', 'limitations' => '{}'],
        ['id' => 2, 'status' => 2, 'role_id' => 2, 'component' => 'block', 'permission' => 'add', 'limitations' => '{}'],
        ['id' => 3, 'status' => 0, 'role_id' => 2, 'component' => 'block', 'permission' => 'edit', 'limitations' => '{"block_definition": ["title","list"]}'],
        ['id' => 3, 'status' => 1, 'role_id' => 2, 'component' => 'block', 'permission' => 'edit', 'limitations' => '{"block_definition": ["title","list"]}'],
        ['id' => 3, 'status' => 2, 'role_id' => 2, 'component' => 'block', 'permission' => 'edit', 'limitations' => '{"block_definition": ["title","list"]}'],
        ['id' => 4, 'status' => 0, 'role_id' => 2, 'component' => 'layout', 'permission' => null, 'limitations' => '{}'],
        ['id' => 4, 'status' => 1, 'role_id' => 2, 'component' => 'layout', 'permission' => null, 'limitations' => '{}'],
        ['id' => 4, 'status' => 2, 'role_id' => 2, 'component' => 'layout', 'permission' => null, 'limitations' => '{}'],
    ],
    'nglayouts_rule' => [
        ['id' => 1, 'status' => 1, 'uuid' => '26768324-03dd-5952-8a55-4b449d6cd634', 'layout_id' => 1, 'comment' => 'My comment'],
        ['id' => 2, 'status' => 1, 'uuid' => '55622437-f700-5378-99c9-7dafe89a8fb6', 'layout_id' => 2, 'comment' => 'My other comment'],
        ['id' => 2, 'status' => 2, 'uuid' => '55622437-f700-5378-99c9-7dafe89a8fb6', 'layout_id' => 2, 'comment' => 'My other comment'],
        ['id' => 3, 'status' => 1, 'uuid' => '23eece92-8cce-5155-9fef-58fb5e3decd6', 'layout_id' => 3, 'comment' => ''],
        ['id' => 4, 'status' => 1, 'uuid' => 'd5bcbdfc-2e75-5f06-8c47-c26d68bb7b5e', 'layout_id' => 1, 'comment' => ''],
        ['id' => 5, 'status' => 0, 'uuid' => 'de086bdf-0014-5f4f-89e4-fc0aff21da90', 'layout_id' => 2, 'comment' => ''],
        ['id' => 5, 'status' => 1, 'uuid' => 'de086bdf-0014-5f4f-89e4-fc0aff21da90', 'layout_id' => 2, 'comment' => ''],
        ['id' => 6, 'status' => 1, 'uuid' => '4f63660c-bd58-5efa-81a8-6c81b4484a61', 'layout_id' => 3, 'comment' => ''],
        ['id' => 7, 'status' => 0, 'uuid' => '816c00bb-8253-5bba-a067-ba6de1f94a65', 'layout_id' => 4, 'comment' => ''],
        ['id' => 7, 'status' => 1, 'uuid' => '816c00bb-8253-5bba-a067-ba6de1f94a65', 'layout_id' => 4, 'comment' => ''],
        ['id' => 8, 'status' => 1, 'uuid' => 'bd5415cb-9447-52ec-bb81-71bb6302d52c', 'layout_id' => 5, 'comment' => ''],
        ['id' => 9, 'status' => 1, 'uuid' => 'af071c3d-96aa-5731-b755-bbc0d407f02d', 'layout_id' => 6, 'comment' => ''],
        ['id' => 10, 'status' => 1, 'uuid' => 'e68f3641-f44a-54d7-ad8d-4649024a1fd2', 'layout_id' => 7, 'comment' => ''],
        ['id' => 11, 'status' => 1, 'uuid' => 'c6891782-9d3e-58b7-95ac-261f491cc1ae', 'layout_id' => null, 'comment' => ''],
        ['id' => 12, 'status' => 1, 'uuid' => 'bc4cbc07-37ff-5893-8176-71cb347c9e2f', 'layout_id' => 7, 'comment' => ''],
    ],
    'nglayouts_rule_data' => [
        ['rule_id' => 1, 'enabled' => 1, 'priority' => 9],
        ['rule_id' => 2, 'enabled' => 1, 'priority' => 8],
        ['rule_id' => 3, 'enabled' => 1, 'priority' => 7],
        ['rule_id' => 4, 'enabled' => 0, 'priority' => 6],
        ['rule_id' => 5, 'enabled' => 1, 'priority' => 5],
        ['rule_id' => 6, 'enabled' => 1, 'priority' => 4],
        ['rule_id' => 7, 'enabled' => 1, 'priority' => 3],
        ['rule_id' => 8, 'enabled' => 1, 'priority' => 2],
        ['rule_id' => 9, 'enabled' => 1, 'priority' => 1],
        ['rule_id' => 10, 'enabled' => 1, 'priority' => 0],
        ['rule_id' => 11, 'enabled' => 0, 'priority' => -1],
        ['rule_id' => 12, 'enabled' => 0, 'priority' => -2],
    ],
    'nglayouts_rule_target' => [
        ['id' => 1, 'status' => 1, 'uuid' => 'c7c5cdca-02da-5ba5-ad9e-d25cbc4b1b46', 'rule_id' => 1, 'type' => 'route', 'value' => 'my_cool_route'],
        ['id' => 2, 'status' => 1, 'uuid' => '0cd23062-3fa7-582f-b022-034595ec68d5', 'rule_id' => 1, 'type' => 'route', 'value' => 'my_other_cool_route'],
        ['id' => 3, 'status' => 1, 'uuid' => '59cbea15-a034-5fcf-ba9b-d59426d6b601', 'rule_id' => 2, 'type' => 'route', 'value' => 'my_second_cool_route'],
        ['id' => 3, 'status' => 2, 'uuid' => '59cbea15-a034-5fcf-ba9b-d59426d6b601', 'rule_id' => 2, 'type' => 'route', 'value' => 'my_second_cool_route'],
        ['id' => 4, 'status' => 1, 'uuid' => '48c8c075-83f0-53f5-8192-4530b6d5a17b', 'rule_id' => 2, 'type' => 'route', 'value' => 'my_third_cool_route'],
        ['id' => 4, 'status' => 2, 'uuid' => '48c8c075-83f0-53f5-8192-4530b6d5a17b', 'rule_id' => 2, 'type' => 'route', 'value' => 'my_third_cool_route'],
        ['id' => 5, 'status' => 1, 'uuid' => '445e885e-1ad5-584b-b51b-263fb66805c2', 'rule_id' => 3, 'type' => 'route', 'value' => 'my_fourth_cool_route'],
        ['id' => 6, 'status' => 1, 'uuid' => 'feee231e-4fee-514a-a938-a2769036c07b', 'rule_id' => 3, 'type' => 'route', 'value' => 'my_fifth_cool_route'],
        ['id' => 7, 'status' => 1, 'uuid' => '5f086fc4-4e1c-55eb-ae54-79fc296cda37', 'rule_id' => 4, 'type' => 'route_prefix', 'value' => 'my_cool_'],
        ['id' => 8, 'status' => 1, 'uuid' => '513e4cb3-c7ab-5657-8bb1-966b4c7e1356', 'rule_id' => 4, 'type' => 'route_prefix', 'value' => 'my_other_cool_'],
        ['id' => 9, 'status' => 0, 'uuid' => '5104e4e7-1a20-5db8-8857-5ab99f1290b9', 'rule_id' => 5, 'type' => 'route_prefix', 'value' => 'my_second_cool_'],
        ['id' => 9, 'status' => 1, 'uuid' => '5104e4e7-1a20-5db8-8857-5ab99f1290b9', 'rule_id' => 5, 'type' => 'route_prefix', 'value' => 'my_second_cool_'],
        ['id' => 10, 'status' => 0, 'uuid' => 'f0019d3e-5868-503d-b81b-5263af428495', 'rule_id' => 5, 'type' => 'route_prefix', 'value' => 'my_third_cool_'],
        ['id' => 10, 'status' => 1, 'uuid' => 'f0019d3e-5868-503d-b81b-5263af428495', 'rule_id' => 5, 'type' => 'route_prefix', 'value' => 'my_third_cool_'],
        ['id' => 11, 'status' => 1, 'uuid' => 'ad2145f9-4efb-56da-944d-8781394040f1', 'rule_id' => 6, 'type' => 'route_prefix', 'value' => 'my_fourth_cool_'],
        ['id' => 12, 'status' => 1, 'uuid' => '86e4bc55-7191-52f7-9a80-f2d461cc4281', 'rule_id' => 6, 'type' => 'route_prefix', 'value' => 'my_fifth_cool_'],
        ['id' => 13, 'status' => 0, 'uuid' => '8c5ad110-f161-5bd8-ae56-c60266dbc4e7', 'rule_id' => 7, 'type' => 'path_info', 'value' => '/the/answer'],
        ['id' => 13, 'status' => 1, 'uuid' => '8c5ad110-f161-5bd8-ae56-c60266dbc4e7', 'rule_id' => 7, 'type' => 'path_info', 'value' => '/the/answer'],
        ['id' => 14, 'status' => 0, 'uuid' => 'b52d3745-bab3-5a92-98f9-4b0d9e97ac34', 'rule_id' => 7, 'type' => 'path_info', 'value' => '/the/other/answer'],
        ['id' => 14, 'status' => 1, 'uuid' => 'b52d3745-bab3-5a92-98f9-4b0d9e97ac34', 'rule_id' => 7, 'type' => 'path_info', 'value' => '/the/other/answer'],
        ['id' => 15, 'status' => 1, 'uuid' => '69b6a052-c8ea-5ce3-9749-8e5b333671bc', 'rule_id' => 8, 'type' => 'path_info_prefix', 'value' => '/the/'],
        ['id' => 16, 'status' => 1, 'uuid' => 'fa160596-4222-55b7-b142-d1affabc1607', 'rule_id' => 8, 'type' => 'path_info_prefix', 'value' => '/a/'],
        ['id' => 17, 'status' => 1, 'uuid' => '12684803-3749-5525-b2ec-7248e48fff0f', 'rule_id' => 9, 'type' => 'request_uri', 'value' => '/the/answer?a=42'],
        ['id' => 18, 'status' => 1, 'uuid' => '9da86bbc-41ef-584b-a48c-f6bc02e16be2', 'rule_id' => 9, 'type' => 'request_uri', 'value' => '/the/answer?a=43'],
        ['id' => 19, 'status' => 1, 'uuid' => '58e1ac00-9470-5085-8db3-201ee951b7d5', 'rule_id' => 10, 'type' => 'request_uri_prefix', 'value' => '/the/'],
        ['id' => 20, 'status' => 1, 'uuid' => '9f23faad-f9fd-5de7-abdf-271fbde9afb7', 'rule_id' => 10, 'type' => 'request_uri_prefix', 'value' => '/a/'],
    ],
    'nglayouts_rule_condition' => [
        ['id' => 1, 'status' => 1, 'uuid' => '35f4594c-6674-5815-add6-07f288b79686', 'rule_id' => 2, 'type' => 'route_parameter', 'value' => '{"parameter_name": "some_param", "parameter_values": [1,2]}'],
        ['id' => 1, 'status' => 2, 'uuid' => '35f4594c-6674-5815-add6-07f288b79686', 'rule_id' => 2, 'type' => 'route_parameter', 'value' => '{"parameter_name": "some_param", "parameter_values": [1,2]}'],
        ['id' => 2, 'status' => 1, 'uuid' => '9a6c8459-5fda-5d4b-b06e-06f637ab6e01', 'rule_id' => 3, 'type' => 'route_parameter', 'value' => '{"parameter_name": "some_param", "parameter_values": [3,4]}'],
        ['id' => 3, 'status' => 1, 'uuid' => 'dd49afcd-aab0-5970-b7b8-413238faf539', 'rule_id' => 3, 'type' => 'route_parameter', 'value' => '{"parameter_name": "some_other_param", "parameter_values": [5,6]}'],
        ['id' => 4, 'status' => 0, 'uuid' => '7db46c94-3139-5a3d-9b2a-b2d28e7573ca', 'rule_id' => 5, 'type' => 'condition1', 'value' => '["some_value"]'],
        ['id' => 4, 'status' => 1, 'uuid' => '7db46c94-3139-5a3d-9b2a-b2d28e7573ca', 'rule_id' => 5, 'type' => 'condition1', 'value' => '["some_value"]'],
    ],
];
