<?php

return [
    'ngbm_layout' => [
        ['id' => 1, 'status' => 0, 'type' => '4_zones_a', 'name' => 'My layout', 'description' => 'My layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 1, 'status' => 1, 'type' => '4_zones_a', 'name' => 'My layout', 'description' => 'My layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 2, 'status' => 0, 'type' => '4_zones_b', 'name' => 'My other layout', 'description' => 'My other layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 2, 'status' => 1, 'type' => '4_zones_b', 'name' => 'My other layout', 'description' => 'My other layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 2, 'status' => 2, 'type' => '4_zones_b', 'name' => '', 'description' => 'My archived layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 3, 'status' => 0, 'type' => '4_zones_b', 'name' => 'My third layout', 'description' => 'My third layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 1, 'main_locale' => 'en'],
        ['id' => 3, 'status' => 1, 'type' => '4_zones_b', 'name' => 'My third layout', 'description' => 'My third layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 1, 'main_locale' => 'en'],
        ['id' => 4, 'status' => 0, 'type' => '4_zones_b', 'name' => 'My fourth layout', 'description' => 'My fourth layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 5, 'status' => 0, 'type' => '4_zones_b', 'name' => 'My fifth layout', 'description' => 'My fifth layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 1, 'main_locale' => 'en'],
        ['id' => 5, 'status' => 1, 'type' => '4_zones_b', 'name' => 'My fifth layout', 'description' => 'My fifth layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 1, 'main_locale' => 'en'],
        ['id' => 6, 'status' => 1, 'type' => '4_zones_b', 'name' => 'My sixth layout', 'description' => 'My sixth layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
        ['id' => 7, 'status' => 0, 'type' => '4_zones_b', 'name' => 'My seventh layout', 'description' => 'My seventh layout description', 'created' => 1447065813, 'modified' => 1447065813, 'shared' => 0, 'main_locale' => 'en'],
    ],
    'ngbm_layout_translation' => [
        ['layout_id' => 1, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 1, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 1, 'status' => 0, 'locale' => 'hr'],
        ['layout_id' => 1, 'status' => 1, 'locale' => 'hr'],
        ['layout_id' => 2, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 2, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 2, 'status' => 2, 'locale' => 'en'],
        ['layout_id' => 3, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 3, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 4, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 5, 'status' => 0, 'locale' => 'en'],
        ['layout_id' => 5, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 6, 'status' => 1, 'locale' => 'en'],
        ['layout_id' => 7, 'status' => 0, 'locale' => 'en'],
    ],
    'ngbm_block' => [
        ['id' => 1, 'status' => 0, 'layout_id' => 1, 'depth' => 0, 'path' => '/1/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 1, 'status' => 1, 'layout_id' => 1, 'depth' => 0, 'path' => '/1/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 2, 'status' => 0, 'layout_id' => 1, 'depth' => 0, 'path' => '/2/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 2, 'status' => 1, 'layout_id' => 1, 'depth' => 0, 'path' => '/2/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 3, 'status' => 0, 'layout_id' => 1, 'depth' => 0, 'path' => '/3/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 3, 'status' => 1, 'layout_id' => 1, 'depth' => 0, 'path' => '/3/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 4, 'status' => 0, 'layout_id' => 1, 'depth' => 0, 'path' => '/4/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 4, 'status' => 1, 'layout_id' => 1, 'depth' => 0, 'path' => '/4/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 5, 'status' => 0, 'layout_id' => 2, 'depth' => 0, 'path' => '/5/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 5, 'status' => 1, 'layout_id' => 2, 'depth' => 0, 'path' => '/5/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 5, 'status' => 2, 'layout_id' => 2, 'depth' => 0, 'path' => '/5/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 0, 'layout_id' => 2, 'depth' => 0, 'path' => '/6/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 1, 'layout_id' => 2, 'depth' => 0, 'path' => '/6/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 2, 'layout_id' => 2, 'depth' => 0, 'path' => '/6/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 7, 'status' => 0, 'layout_id' => 2, 'depth' => 0, 'path' => '/7/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 7, 'status' => 1, 'layout_id' => 2, 'depth' => 0, 'path' => '/7/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 7, 'status' => 2, 'layout_id' => 2, 'depth' => 0, 'path' => '/7/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 8, 'status' => 0, 'layout_id' => 2, 'depth' => 0, 'path' => '/8/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 8, 'status' => 1, 'layout_id' => 2, 'depth' => 0, 'path' => '/8/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 8, 'status' => 2, 'layout_id' => 2, 'depth' => 0, 'path' => '/8/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 9, 'status' => 0, 'layout_id' => 3, 'depth' => 0, 'path' => '/9/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 9, 'status' => 1, 'layout_id' => 3, 'depth' => 0, 'path' => '/9/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 10, 'status' => 0, 'layout_id' => 3, 'depth' => 0, 'path' => '/10/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 10, 'status' => 1, 'layout_id' => 3, 'depth' => 0, 'path' => '/10/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 11, 'status' => 0, 'layout_id' => 3, 'depth' => 0, 'path' => '/11/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 11, 'status' => 1, 'layout_id' => 3, 'depth' => 0, 'path' => '/11/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 12, 'status' => 0, 'layout_id' => 3, 'depth' => 0, 'path' => '/12/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 12, 'status' => 1, 'layout_id' => 3, 'depth' => 0, 'path' => '/12/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 13, 'status' => 0, 'layout_id' => 4, 'depth' => 0, 'path' => '/13/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 14, 'status' => 0, 'layout_id' => 4, 'depth' => 0, 'path' => '/14/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 15, 'status' => 0, 'layout_id' => 4, 'depth' => 0, 'path' => '/15/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 16, 'status' => 0, 'layout_id' => 4, 'depth' => 0, 'path' => '/16/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 17, 'status' => 0, 'layout_id' => 5, 'depth' => 0, 'path' => '/17/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 17, 'status' => 1, 'layout_id' => 5, 'depth' => 0, 'path' => '/17/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 18, 'status' => 0, 'layout_id' => 5, 'depth' => 0, 'path' => '/18/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 18, 'status' => 1, 'layout_id' => 5, 'depth' => 0, 'path' => '/18/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 19, 'status' => 0, 'layout_id' => 5, 'depth' => 0, 'path' => '/19/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 19, 'status' => 1, 'layout_id' => 5, 'depth' => 0, 'path' => '/19/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 20, 'status' => 0, 'layout_id' => 5, 'depth' => 0, 'path' => '/20/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 20, 'status' => 1, 'layout_id' => 5, 'depth' => 0, 'path' => '/20/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 21, 'status' => 1, 'layout_id' => 6, 'depth' => 0, 'path' => '/21/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 22, 'status' => 1, 'layout_id' => 6, 'depth' => 0, 'path' => '/22/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 23, 'status' => 1, 'layout_id' => 6, 'depth' => 0, 'path' => '/23/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 24, 'status' => 1, 'layout_id' => 6, 'depth' => 0, 'path' => '/24/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 25, 'status' => 0, 'layout_id' => 7, 'depth' => 0, 'path' => '/25/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 26, 'status' => 0, 'layout_id' => 7, 'depth' => 0, 'path' => '/26/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 27, 'status' => 0, 'layout_id' => 7, 'depth' => 0, 'path' => '/27/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 28, 'status' => 0, 'layout_id' => 7, 'depth' => 0, 'path' => '/28/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 29, 'status' => 0, 'layout_id' => 7, 'depth' => 0, 'path' => '/29/', 'parent_id' => null, 'placeholder' => null, 'position' => null, 'definition_identifier' => '', 'view_type' => '', 'item_view_type' => '', 'name' => '', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 31, 'status' => 0, 'layout_id' => 1, 'depth' => 1, 'path' => '/3/31/', 'parent_id' => 3, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'list', 'view_type' => 'list', 'item_view_type' => 'standard', 'name' => 'My block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 31, 'status' => 1, 'layout_id' => 1, 'depth' => 1, 'path' => '/3/31/', 'parent_id' => 3, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard_with_intro', 'name' => 'My published block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 32, 'status' => 0, 'layout_id' => 1, 'depth' => 1, 'path' => '/2/32/', 'parent_id' => 2, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard', 'name' => 'My other block', 'config' => '{"http_cache": {"use_http_cache": false}}', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 32, 'status' => 1, 'layout_id' => 1, 'depth' => 1, 'path' => '/2/32/', 'parent_id' => 2, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard', 'name' => 'My other block', 'config' => '{"http_cache": {"use_http_cache": false}}', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 33, 'status' => 0, 'layout_id' => 2, 'depth' => 1, 'path' => '/7/33/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'two_columns', 'view_type' => 'two_columns_50_50', 'item_view_type' => 'standard', 'name' => 'My third block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 33, 'status' => 1, 'layout_id' => 2, 'depth' => 1, 'path' => '/7/33/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'two_columns', 'view_type' => 'two_columns_50_50', 'item_view_type' => 'standard', 'name' => 'My third block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 33, 'status' => 2, 'layout_id' => 2, 'depth' => 1, 'path' => '/7/33/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'two_columns', 'view_type' => 'two_columns_50_50', 'item_view_type' => 'standard', 'name' => 'My third block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 34, 'status' => 0, 'layout_id' => 2, 'depth' => 1, 'path' => '/6/34/', 'parent_id' => 6, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'title', 'view_type' => 'title', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 34, 'status' => 1, 'layout_id' => 2, 'depth' => 1, 'path' => '/6/34/', 'parent_id' => 6, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'title', 'view_type' => 'title', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 34, 'status' => 2, 'layout_id' => 2, 'depth' => 1, 'path' => '/6/34/', 'parent_id' => 6, 'placeholder' => 'root', 'position' => 0, 'definition_identifier' => 'title', 'view_type' => 'title', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 35, 'status' => 0, 'layout_id' => 1, 'depth' => 1, 'path' => '/3/35/', 'parent_id' => 3, 'placeholder' => 'root', 'position' => 1, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 35, 'status' => 1, 'layout_id' => 1, 'depth' => 1, 'path' => '/3/35/', 'parent_id' => 3, 'placeholder' => 'root', 'position' => 1, 'definition_identifier' => 'list', 'view_type' => 'grid', 'item_view_type' => 'standard', 'name' => 'My fourth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 36, 'status' => 0, 'layout_id' => 2, 'depth' => 1, 'path' => '/7/36/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 1, 'definition_identifier' => 'title', 'view_type' => 'title', 'item_view_type' => 'standard', 'name' => 'My sixth block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 37, 'status' => 0, 'layout_id' => 2, 'depth' => 2, 'path' => '/7/33/37/', 'parent_id' => 33, 'placeholder' => 'left', 'position' => 0, 'definition_identifier' => 'text', 'view_type' => 'text', 'item_view_type' => 'standard', 'name' => 'My seventh block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 37, 'status' => 1, 'layout_id' => 2, 'depth' => 2, 'path' => '/7/33/37/', 'parent_id' => 33, 'placeholder' => 'left', 'position' => 0, 'definition_identifier' => 'text', 'view_type' => 'text', 'item_view_type' => 'standard', 'name' => 'My seventh block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 37, 'status' => 2, 'layout_id' => 2, 'depth' => 2, 'path' => '/7/33/37/', 'parent_id' => 33, 'placeholder' => 'left', 'position' => 0, 'definition_identifier' => 'text', 'view_type' => 'text', 'item_view_type' => 'standard', 'name' => 'My seventh block', 'config' => '', 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 38, 'status' => 0, 'layout_id' => 2, 'depth' => 1, 'path' => '/7/38/', 'parent_id' => 7, 'placeholder' => 'root', 'position' => 2, 'definition_identifier' => 'column', 'view_type' => 'column', 'item_view_type' => 'standard', 'name' => 'My eight block', 'config' => '', 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
    ],
    'ngbm_block_translation' => [
        ['block_id' => 1, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 1, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 2, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 2, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 3, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 3, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 4, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 4, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 5, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 5, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 5, 'status' => 2, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 6, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 6, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 6, 'status' => 2, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 7, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 7, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 7, 'status' => 2, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 8, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 8, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 8, 'status' => 2, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 9, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 9, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 10, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 10, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 11, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 11, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 12, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 12, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 13, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 14, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 15, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 16, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 17, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 17, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 18, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 18, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 19, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 19, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 20, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 20, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 21, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 22, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 23, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 24, 'status' => 1, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 25, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 26, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 27, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 28, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 29, 'status' => 0, 'locale' => 'en', 'parameters' => ''],
        ['block_id' => 31, 'status' => 0, 'locale' => 'en', 'parameters' => '{"number_of_columns": 2, "css_class": "css-class", "css_id": "css-id"}'],
        ['block_id' => 31, 'status' => 1, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 31, 'status' => 0, 'locale' => 'hr', 'parameters' => '{"css_class": "css-class-hr", "css_id": "css-id"}'],
        ['block_id' => 31, 'status' => 1, 'locale' => 'hr', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 32, 'status' => 0, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 32, 'status' => 1, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 32, 'status' => 0, 'locale' => 'hr', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 32, 'status' => 1, 'locale' => 'hr', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 33, 'status' => 0, 'locale' => 'en', 'parameters' => '{}'],
        ['block_id' => 33, 'status' => 1, 'locale' => 'en', 'parameters' => '{}'],
        ['block_id' => 33, 'status' => 2, 'locale' => 'en', 'parameters' => '{}'],
        ['block_id' => 34, 'status' => 0, 'locale' => 'en', 'parameters' => '{"tag": "h3", "title": "Title"}'],
        ['block_id' => 34, 'status' => 1, 'locale' => 'en', 'parameters' => '{"tag": "h3", "title": "Title"}'],
        ['block_id' => 34, 'status' => 2, 'locale' => 'en', 'parameters' => '{"tag": "h3", "title": "Title"}'],
        ['block_id' => 35, 'status' => 0, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 35, 'status' => 1, 'locale' => 'en', 'parameters' => '{"number_of_columns": 3}'],
        ['block_id' => 36, 'status' => 0, 'locale' => 'en', 'parameters' => '{"tag": "h3", "title": "Title", "css_class": "CSS class"}'],
        ['block_id' => 37, 'status' => 0, 'locale' => 'en', 'parameters' => '{"content": "Text"}'],
        ['block_id' => 37, 'status' => 1, 'locale' => 'en', 'parameters' => '{"content": "Text"}'],
        ['block_id' => 37, 'status' => 2, 'locale' => 'en', 'parameters' => '{"content": "Text"}'],
        ['block_id' => 38, 'status' => 0, 'locale' => 'en', 'parameters' => '{}'],
    ],
    'ngbm_zone' => [
        ['identifier' => 'top', 'layout_id' => 1, 'status' => 0, 'root_block_id' => 1, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 1, 'status' => 1, 'root_block_id' => 1, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 1, 'status' => 0, 'root_block_id' => 2, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 1, 'status' => 1, 'root_block_id' => 2, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 1, 'status' => 0, 'root_block_id' => 3, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 1, 'status' => 1, 'root_block_id' => 3, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 1, 'status' => 0, 'root_block_id' => 4, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 1, 'status' => 1, 'root_block_id' => 4, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 2, 'status' => 0, 'root_block_id' => 5, 'linked_layout_id' => 3, 'linked_zone_identifier' => 'top'],
        ['identifier' => 'top', 'layout_id' => 2, 'status' => 1, 'root_block_id' => 5, 'linked_layout_id' => 3, 'linked_zone_identifier' => 'top'],
        ['identifier' => 'top', 'layout_id' => 2, 'status' => 2, 'root_block_id' => 5, 'linked_layout_id' => 3, 'linked_zone_identifier' => 'top'],
        ['identifier' => 'left', 'layout_id' => 2, 'status' => 0, 'root_block_id' => 6, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 2, 'status' => 1, 'root_block_id' => 6, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 2, 'status' => 2, 'root_block_id' => 6, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 2, 'status' => 0, 'root_block_id' => 7, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 2, 'status' => 1, 'root_block_id' => 7, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 2, 'status' => 2, 'root_block_id' => 7, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 2, 'status' => 0, 'root_block_id' => 8, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 2, 'status' => 1, 'root_block_id' => 8, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 2, 'status' => 2, 'root_block_id' => 8, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 3, 'status' => 0, 'root_block_id' => 9, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 3, 'status' => 0, 'root_block_id' => 10, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 3, 'status' => 0, 'root_block_id' => 11, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 3, 'status' => 0, 'root_block_id' => 12, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 3, 'status' => 1, 'root_block_id' => 9, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 3, 'status' => 1, 'root_block_id' => 10, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 3, 'status' => 1, 'root_block_id' => 11, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 3, 'status' => 1, 'root_block_id' => 12, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 4, 'status' => 0, 'root_block_id' => 13, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 4, 'status' => 0, 'root_block_id' => 14, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 4, 'status' => 0, 'root_block_id' => 15, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 4, 'status' => 0, 'root_block_id' => 16, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 5, 'status' => 0, 'root_block_id' => 17, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 5, 'status' => 0, 'root_block_id' => 18, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 5, 'status' => 0, 'root_block_id' => 19, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 5, 'status' => 0, 'root_block_id' => 20, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 5, 'status' => 1, 'root_block_id' => 17, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 5, 'status' => 1, 'root_block_id' => 18, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 5, 'status' => 1, 'root_block_id' => 19, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 5, 'status' => 1, 'root_block_id' => 20, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 6, 'status' => 1, 'root_block_id' => 21, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 6, 'status' => 1, 'root_block_id' => 22, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 6, 'status' => 1, 'root_block_id' => 23, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 6, 'status' => 1, 'root_block_id' => 24, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'top', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 25, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'left', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 26, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'right', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 27, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        ['identifier' => 'bottom', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 28, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
        // This zone does not exist in a layout but is used in tests for layouts which had it's layout type config changed
        ['identifier' => 'center', 'layout_id' => 7, 'status' => 0, 'root_block_id' => 29, 'linked_layout_id' => null, 'linked_zone_identifier' => null],
    ],
    'ngbm_collection' => [
        ['id' => 1, 'status' => 0, 'start' => 0, 'length' => null, 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 2, 'status' => 1, 'start' => 0, 'length' => null, 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 3, 'status' => 0, 'start' => 4, 'length' => 2, 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 3, 'status' => 1, 'start' => 4, 'length' => 2, 'main_locale' => 'en', 'translatable' => 1, 'always_available' => 1],
        ['id' => 4, 'status' => 0, 'start' => 0, 'length' => null, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 4, 'status' => 1, 'start' => 0, 'length' => null, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 0, 'start' => 10, 'length' => 5, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 1, 'start' => 10, 'length' => 5, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
        ['id' => 6, 'status' => 2, 'start' => 10, 'length' => 5, 'main_locale' => 'en', 'translatable' => 0, 'always_available' => 1],
    ],
    'ngbm_collection_translation' => [
        ['collection_id' => 1, 'status' => 0, 'locale' => 'en'],
        ['collection_id' => 1, 'status' => 0, 'locale' => 'hr'],
        ['collection_id' => 2, 'status' => 1, 'locale' => 'en'],
        ['collection_id' => 2, 'status' => 1, 'locale' => 'hr'],
        ['collection_id' => 3, 'status' => 0, 'locale' => 'en'],
        ['collection_id' => 3, 'status' => 0, 'locale' => 'hr'],
        ['collection_id' => 3, 'status' => 1, 'locale' => 'en'],
        ['collection_id' => 3, 'status' => 1, 'locale' => 'hr'],
        ['collection_id' => 4, 'status' => 0, 'locale' => 'en'],
        ['collection_id' => 4, 'status' => 1, 'locale' => 'en'],
        ['collection_id' => 6, 'status' => 0, 'locale' => 'en'],
        ['collection_id' => 6, 'status' => 1, 'locale' => 'en'],
        ['collection_id' => 6, 'status' => 2, 'locale' => 'en'],
    ],
    'ngbm_collection_item' => [
        ['id' => 1, 'status' => 0, 'collection_id' => 1, 'position' => 0, 'type' => 0, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 2, 'status' => 0, 'collection_id' => 1, 'position' => 1, 'type' => 0, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 3, 'status' => 0, 'collection_id' => 1, 'position' => 2, 'type' => 0, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 4, 'status' => 1, 'collection_id' => 2, 'position' => 1, 'type' => 0, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 5, 'status' => 1, 'collection_id' => 2, 'position' => 2, 'type' => 0, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 6, 'status' => 1, 'collection_id' => 2, 'position' => 5, 'type' => 0, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 7, 'status' => 0, 'collection_id' => 3, 'position' => 2, 'type' => 0, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 7, 'status' => 1, 'collection_id' => 3, 'position' => 2, 'type' => 0, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 8, 'status' => 0, 'collection_id' => 3, 'position' => 3, 'type' => 0, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 8, 'status' => 1, 'collection_id' => 3, 'position' => 3, 'type' => 0, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 9, 'status' => 0, 'collection_id' => 3, 'position' => 5, 'type' => 0, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 9, 'status' => 1, 'collection_id' => 3, 'position' => 5, 'type' => 0, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 10, 'status' => 0, 'collection_id' => 4, 'position' => 2, 'type' => 0, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 10, 'status' => 1, 'collection_id' => 4, 'position' => 2, 'type' => 0, 'value' => '72', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 11, 'status' => 0, 'collection_id' => 4, 'position' => 3, 'type' => 0, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 11, 'status' => 1, 'collection_id' => 4, 'position' => 3, 'type' => 0, 'value' => '73', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 12, 'status' => 0, 'collection_id' => 4, 'position' => 5, 'type' => 0, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
        ['id' => 12, 'status' => 1, 'collection_id' => 4, 'position' => 5, 'type' => 0, 'value' => '74', 'value_type' => 'my_value_type', 'config' => ''],
    ],
    'ngbm_collection_query' => [
        ['id' => 1, 'status' => 1, 'collection_id' => 2, 'type' => 'my_query_type'],
        ['id' => 2, 'status' => 0, 'collection_id' => 3, 'type' => 'my_query_type'],
        ['id' => 2, 'status' => 1, 'collection_id' => 3, 'type' => 'my_query_type'],
        ['id' => 4, 'status' => 0, 'collection_id' => 4, 'type' => 'my_query_type'],
        ['id' => 4, 'status' => 1, 'collection_id' => 4, 'type' => 'my_query_type'],
    ],
    'ngbm_collection_query_translation' => [
        ['query_id' => 1, 'status' => 1, 'locale' => 'en', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 1, 'status' => 1, 'locale' => 'hr', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 2, 'status' => 0, 'locale' => 'en', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 2, 'status' => 0, 'locale' => 'hr', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 2, 'status' => 1, 'locale' => 'en', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 2, 'status' => 1, 'locale' => 'hr', 'parameters' => '{"parent_location_id": 2, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 4, 'status' => 0, 'locale' => 'en', 'parameters' => '{"parent_location_id": 71, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
        ['query_id' => 4, 'status' => 1, 'locale' => 'en', 'parameters' => '{"parent_location_id": 71, "sort_direction": "descending", "sort_type": "date_published", "query_type": "list"}'],
    ],
    'ngbm_block_collection' => [
        ['block_id' => 31, 'block_status' => 0, 'collection_id' => 1, 'collection_status' => 0, 'identifier' => 'default'],
        ['block_id' => 31, 'block_status' => 0, 'collection_id' => 3, 'collection_status' => 0, 'identifier' => 'featured'],
        ['block_id' => 31, 'block_status' => 1, 'collection_id' => 2, 'collection_status' => 1, 'identifier' => 'default'],
        ['block_id' => 31, 'block_status' => 1, 'collection_id' => 3, 'collection_status' => 1, 'identifier' => 'featured'],
        ['block_id' => 35, 'block_status' => 0, 'collection_id' => 4, 'collection_status' => 0, 'identifier' => 'default'],
        ['block_id' => 35, 'block_status' => 1, 'collection_id' => 4, 'collection_status' => 1, 'identifier' => 'default'],
        ['block_id' => 37, 'block_status' => 0, 'collection_id' => 6, 'collection_status' => 0, 'identifier' => 'default'],
        ['block_id' => 37, 'block_status' => 1, 'collection_id' => 6, 'collection_status' => 1, 'identifier' => 'default'],
        ['block_id' => 37, 'block_status' => 2, 'collection_id' => 6, 'collection_status' => 2, 'identifier' => 'default'],
    ],
    'ngbm_rule' => [
        ['id' => 1, 'status' => 1, 'layout_id' => 1, 'comment' => 'My comment'],
        ['id' => 2, 'status' => 1, 'layout_id' => 2, 'comment' => 'My other comment'],
        ['id' => 2, 'status' => 2, 'layout_id' => 2, 'comment' => 'My other comment'],
        ['id' => 3, 'status' => 1, 'layout_id' => 3, 'comment' => null],
        ['id' => 4, 'status' => 1, 'layout_id' => 1, 'comment' => null],
        ['id' => 5, 'status' => 0, 'layout_id' => 2, 'comment' => null],
        ['id' => 5, 'status' => 1, 'layout_id' => 2, 'comment' => null],
        ['id' => 6, 'status' => 1, 'layout_id' => 3, 'comment' => null],
        ['id' => 7, 'status' => 0, 'layout_id' => 4, 'comment' => null],
        ['id' => 7, 'status' => 1, 'layout_id' => 4, 'comment' => null],
        ['id' => 8, 'status' => 1, 'layout_id' => 5, 'comment' => null],
        ['id' => 9, 'status' => 1, 'layout_id' => 6, 'comment' => null],
        ['id' => 10, 'status' => 1, 'layout_id' => 7, 'comment' => null],
        ['id' => 11, 'status' => 1, 'layout_id' => null, 'comment' => null],
        ['id' => 12, 'status' => 1, 'layout_id' => 7, 'comment' => null],
    ],
    'ngbm_rule_data' => [
        ['rule_id' => 1, 'enabled' => 1, 'priority' => 9],
        ['rule_id' => 2, 'enabled' => 1, 'priority' => 8],
        ['rule_id' => 3, 'enabled' => 1, 'priority' => 7],
        ['rule_id' => 4, 'enabled' => 0, 'priority' => 6],
        ['rule_id' => 5, 'enabled' => 1, 'priority' => 5],
        ['rule_id' => 6, 'enabled' => 1, 'priority' => 4],
        ['rule_id' => 7, 'enabled' => 1, 'priority' => 3],
        ['rule_id' => 8, 'enabled' => 1, 'priority' => 2],
        ['rule_id' => 9, 'enabled' => 1, 'priority' => 1],
        ['rule_id' => 10, 'enabled' => 1, 'priority' => 0],
        ['rule_id' => 11, 'enabled' => 0, 'priority' => -1],
        ['rule_id' => 12, 'enabled' => 0, 'priority' => -2],
    ],
    'ngbm_rule_target' => [
        ['id' => 1, 'status' => 1, 'rule_id' => 1, 'type' => 'route', 'value' => 'my_cool_route'],
        ['id' => 2, 'status' => 1, 'rule_id' => 1, 'type' => 'route', 'value' => 'my_other_cool_route'],
        ['id' => 3, 'status' => 1, 'rule_id' => 2, 'type' => 'route', 'value' => 'my_second_cool_route'],
        ['id' => 3, 'status' => 2, 'rule_id' => 2, 'type' => 'route', 'value' => 'my_second_cool_route'],
        ['id' => 4, 'status' => 1, 'rule_id' => 2, 'type' => 'route', 'value' => 'my_third_cool_route'],
        ['id' => 4, 'status' => 2, 'rule_id' => 2, 'type' => 'route', 'value' => 'my_third_cool_route'],
        ['id' => 5, 'status' => 1, 'rule_id' => 3, 'type' => 'route', 'value' => 'my_fourth_cool_route'],
        ['id' => 6, 'status' => 1, 'rule_id' => 3, 'type' => 'route', 'value' => 'my_fifth_cool_route'],
        ['id' => 7, 'status' => 1, 'rule_id' => 4, 'type' => 'route_prefix', 'value' => 'my_cool_'],
        ['id' => 8, 'status' => 1, 'rule_id' => 4, 'type' => 'route_prefix', 'value' => 'my_other_cool_'],
        ['id' => 9, 'status' => 0, 'rule_id' => 5, 'type' => 'route_prefix', 'value' => 'my_second_cool_'],
        ['id' => 9, 'status' => 1, 'rule_id' => 5, 'type' => 'route_prefix', 'value' => 'my_second_cool_'],
        ['id' => 10, 'status' => 0, 'rule_id' => 5, 'type' => 'route_prefix', 'value' => 'my_third_cool_'],
        ['id' => 10, 'status' => 1, 'rule_id' => 5, 'type' => 'route_prefix', 'value' => 'my_third_cool_'],
        ['id' => 11, 'status' => 1, 'rule_id' => 6, 'type' => 'route_prefix', 'value' => 'my_fourth_cool_'],
        ['id' => 12, 'status' => 1, 'rule_id' => 6, 'type' => 'route_prefix', 'value' => 'my_fifth_cool_'],
        ['id' => 13, 'status' => 0, 'rule_id' => 7, 'type' => 'path_info', 'value' => '/the/answer'],
        ['id' => 13, 'status' => 1, 'rule_id' => 7, 'type' => 'path_info', 'value' => '/the/answer'],
        ['id' => 14, 'status' => 0, 'rule_id' => 7, 'type' => 'path_info', 'value' => '/the/other/answer'],
        ['id' => 14, 'status' => 1, 'rule_id' => 7, 'type' => 'path_info', 'value' => '/the/other/answer'],
        ['id' => 15, 'status' => 1, 'rule_id' => 8, 'type' => 'path_info_prefix', 'value' => '/the/'],
        ['id' => 16, 'status' => 1, 'rule_id' => 8, 'type' => 'path_info_prefix', 'value' => '/a/'],
        ['id' => 17, 'status' => 1, 'rule_id' => 9, 'type' => 'request_uri', 'value' => '/the/answer?a=42'],
        ['id' => 18, 'status' => 1, 'rule_id' => 9, 'type' => 'request_uri', 'value' => '/the/answer?a=43'],
        ['id' => 19, 'status' => 1, 'rule_id' => 10, 'type' => 'request_uri_prefix', 'value' => '/the/'],
        ['id' => 20, 'status' => 1, 'rule_id' => 10, 'type' => 'request_uri_prefix', 'value' => '/a/'],
    ],
    'ngbm_rule_condition' => [
        ['id' => 1, 'status' => 1, 'rule_id' => 2, 'type' => 'route_parameter', 'value' => '{"parameter_name": "some_param", "parameter_values": [1,2]}'],
        ['id' => 1, 'status' => 2, 'rule_id' => 2, 'type' => 'route_parameter', 'value' => '{"parameter_name": "some_param", "parameter_values": [1,2]}'],
        ['id' => 2, 'status' => 1, 'rule_id' => 3, 'type' => 'route_parameter', 'value' => '{"parameter_name": "some_param", "parameter_values": [3,4]}'],
        ['id' => 3, 'status' => 1, 'rule_id' => 3, 'type' => 'route_parameter', 'value' => '{"parameter_name": "some_other_param", "parameter_values": [5,6]}'],
        ['id' => 4, 'status' => 0, 'rule_id' => 5, 'type' => 'my_condition', 'value' => '["some_value"]'],
        ['id' => 4, 'status' => 1, 'rule_id' => 5, 'type' => 'my_condition', 'value' => '["some_value"]'],
    ],
];
