services:
    netgen_layouts.collection.item_definition_factory:
        class: Netgen\Layouts\Collection\Item\ItemDefinitionFactory
        arguments:
            - "@netgen_layouts.config.config_definition_factory"

    netgen_layouts.collection.item_visibility_resolver:
        class: Netgen\Layouts\Collection\Item\VisibilityResolver
        arguments:
            - !tagged netgen_layouts.item_visibility_voter

    netgen_layouts.collection.collection_runner_factory:
        class: Netgen\Layouts\Collection\Result\CollectionRunnerFactory
        arguments:
            - "@netgen_layouts.item.item_builder"
            - "@netgen_layouts.collection.item_visibility_resolver"

    netgen_layouts.collection.result_builder:
        class: Netgen\Layouts\Collection\Result\ResultBuilder
        arguments:
            - "@netgen_layouts.collection.collection_runner_factory"
            - "%netgen_layouts.collection.contextual_limit%"
            - "%netgen_layouts.collection.max_limit%"

    netgen_layouts.collection.result.pagerfanta.factory:
        class: Netgen\Layouts\Collection\Result\Pagerfanta\PagerFactory
        arguments:
            - "@netgen_layouts.collection.result_builder"
            - "%netgen_layouts.collection.max_limit%"

    netgen_layouts.collection.result.pagerfanta.view:
        class: Netgen\Layouts\Collection\Result\Pagerfanta\View\CollectionView
        arguments:
            - "@twig"
            - "%netgen_layouts.collection.pager.template%"

    netgen_layouts.collection.query_type_factory:
        class: Netgen\Layouts\Collection\QueryType\QueryTypeFactory
        arguments:
            - "@netgen_layouts.parameters.translatable_parameter_builder_factory"

    netgen_layouts.collection.registry.item_definition:
        class: Netgen\Layouts\Collection\Registry\ItemDefinitionRegistry
        arguments:
            - []

    netgen_layouts.collection.registry.query_type:
        class: Netgen\Layouts\Collection\Registry\QueryTypeRegistry
        public: true
        arguments:
            - []
