services:
    netgen_layouts.templating.plugin_renderer:
        class: Netgen\Bundle\LayoutsBundle\Templating\Plugin\Renderer
        arguments:
            - "@twig"
            - []

    netgen_layouts.templating.global_variable:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\GlobalVariable
        arguments:
            - "@netgen_layouts.configuration"
            - "@netgen_layouts.layout.resolver"
            - "@netgen_layouts.templating.pagelayout_resolver"
            - "@netgen_layouts.view.view_builder"
            - "@netgen_layouts.context"
            - "@uri_signer"
            - "@request_stack"
            - "%netgen_layouts.debug%"

    netgen_layouts.templating.twig.extension.rendering:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\RenderingExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.templating.twig.runtime.rendering.simple_twig:
        class: Twig\Environment
        arguments:
            - !service { class: Twig\Loader\ArrayLoader }
        calls:
            - [addExtension, ["@twig.extension.trans"]]

    netgen_layouts.templating.twig.runtime.rendering:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\RenderingRuntime
        arguments:
            - "@netgen_layouts.api.service.block"
            - "@netgen_layouts.view.renderer"
            - "@netgen_layouts.locale.provider"
            - "@request_stack"
            - "@netgen_layouts.error.handler"
            - "@netgen_layouts.templating.twig.runtime.rendering.simple_twig"
        tags:
            - { name: twig.runtime }

    netgen_layouts.templating.twig.extension.plugin_rendering:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\PluginRenderingExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.templating.twig.runtime.plugin_rendering:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\PluginRenderingRuntime
        arguments:
            - "@netgen_layouts.templating.plugin_renderer"
            - "@netgen_layouts.error.handler"
        tags:
            - { name: twig.runtime }

    netgen_layouts.templating.twig.extension.collection_pager:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\CollectionPagerExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.templating.twig.runtime.collection_pager:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\CollectionPagerRuntime
        arguments:
            - "@netgen_layouts.templating.twig.runtime.collection_pager.route_generator"
            - "@netgen_layouts.collection.result.pagerfanta.view"
        tags:
            - { name: twig.runtime }

    netgen_layouts.templating.twig.runtime.collection_pager.route_generator:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\CollectionPager\RouteGenerator
        arguments:
            - "@netgen_layouts.context"
            - "@uri_signer"
            - "@router"
            - "@request_stack"

    netgen_layouts.templating.twig.extension.item:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\ItemExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.templating.twig.runtime.item:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\ItemRuntime
        arguments:
            - "@netgen_layouts.item.item_loader"
            - "@netgen_layouts.item.url_generator"
            - "@netgen_layouts.error.handler"
        tags:
            - { name: twig.runtime }

    netgen_layouts.templating.twig.extension.helpers:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Extension\HelpersExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.templating.twig.runtime.helpers:
        class: Netgen\Bundle\LayoutsBundle\Templating\Twig\Runtime\HelpersRuntime
        arguments:
            - "@netgen_layouts.api.service.layout"
            - "@netgen_layouts.api.service.layout_resolver"
            - "@netgen_layouts.item.registry.value_type"
        tags:
            - { name: twig.runtime }

    netgen_layouts.templating.twig.extension.version:
        class: EdiModric\Twig\VersionExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.templating.pagelayout_resolver.default:
        class: Netgen\Bundle\LayoutsBundle\Templating\PageLayoutResolver
        arguments:
            - "%netgen_layouts.pagelayout%"

    netgen_layouts.templating.pagelayout_resolver:
        alias: netgen_layouts.templating.pagelayout_resolver.default
